### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by krrishnarraj** [anntzer/clahe#2]
Can we have this package on https://pypi.org ?
It will be easy to do pip install

**Comment by anntzer** [comment]
You can do `pip install git+https://github.com/anntzer/clahe`.  Will update the README accordingly.

**Comment by krrishnarraj** [comment]
I had been doing that for local install. But we can't add git+url as a dependency in setup.py of another package which depends on clahe. We can only add pypi packages in setup.py. I was trying to get around that

**Comment by anntzer** [comment]
Fair enough, it's now at https://pypi.org/project/clahe/.

**Comment by krrishnarraj** [comment]
Thanks
