### ISSUE TITLE
Parameter Type

### ISSUE THREAD

**Issue by tom-xingshuo** [anntzer/clahe#3]
Can you provide a parameter type?

**Comment by anntzer** [comment]
I do not understand your request.

**Comment by tom-xingshuo** [comment]
> I do not understand your request.

Such as `def clahe(img, win_shape, clip_limit, *, _fast=True):`, what is the input for the `win_shape`?

**Comment by tom-xingshuo** [comment]
> I do not understand your request.

When I run this program, it's very slow. And its inputs and outputs are the same.

**Comment by anntzer** [comment]
I have added some docs.  See discussion at https://github.com/scikit-image/scikit-image/issues/2219 wrt. speed.  Consider using the skimage version instead.
